# env=prod helmfile -f helmfile.d/echo-server.yaml diff

releases:
- name: echo-server
  namespace: {{ requiredEnv "env" }}
  chart: ../charts/microservice
  wait: true
  atomic: true
  values:
  - name: echo-server
    port: 5678
    targetPort: 5678
    pod:
      imageName: hashicorp/http-echo
      imageTag: latest
    svc:
      nodePort: 30100
    ing:
      hostname: echo.rms1000watt.com
