apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
    protocol: TCP
    {{- if not .Values.svc.nodePortDynamicPort }}
    nodePort: {{ .Values.svc.nodePort }}
    {{- end }}
  selector:
    run: {{ .Values.name }}
